<a href="https://colab.research.google.com/github/tiravata/2014-slides/blob/master/133_tutorial_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div><img height="45px" src="https://avatars3.githubusercontent.com/u/20337240?s=460&v=4" align="left" hspace="10px" vspace="0px">
</div>
<h1>ติวเตอร์ Tensor Flow</h1>

<hr>

<a href='https://www.facebook.com/programmerthai'><font color='green'>สรุปและเรียบเรียงโดย โปรแกรมเมอร์ไทย thai programmer</font></a>



cite

https://colab.research.google.com/github/madewithml/lessons/blob/master/notebooks/01_Foundations/05_TensorFlow.ipynb

# วิธีใช้งาน colab

Colab พัฒนาโดย google เป็นหน้าเว็บเอาไว้ใช้เขียนโค้ด python ได้ผ่านทางหน้าเว็บ และเชื่อมต่อกับ google drive ของเราก็ได้ด้วย ซึ่ง colab หน้านี้**ได้รวบรวมเนื้อหา Python ของม.ต้น** เอาไว้ แต่ก่อนอื่นอยากให้ดูวิธีการใช้งาน colab เสียก่อน

<font color='red'>** ต้องมี Gmail และ google drive</font>

<hr/>

<h3>วิธี 1) กด "Open in playgrouhd"</h3>
<div>
<img height="200px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2020/05/python_matayom_4.png" align="center" hspace="10px" vspace="0px">


<hr/>

<h3>วิธี 2) กด Save a copy in Drive ... เพื่อบันทึกไว้ google drive เครื่องเรา</h3>

<img height="300px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2019/11/python_matayom_1.png" align="center" hspace="10px" vspace="0px">

<br/>

<img height="200px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2019/11/python_matayom_2.png" align="center" hspace="10px" vspace="0px">

<hr/>

<h3>จากนั้นถึงจะสามารถรันได้</h3>
<img height="200px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2019/11/python_matayom_3.png" align="center" hspace="10px" vspace="0px">

# Set Enviroment

In [ ]:
%tensorflow_version 2.x
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.2.0


# ใช้งาน GPUs

In [ ]:
# Is CUDA available?
print (tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


ถ้า CUDA ไม่ได้เปิดใช้งาน

แนะนำให้ไปที่  *Runtime* > *Change runtime type* > Change *Hardware accelertor* to *GPU* > Click *Save*

# Set seeds

In [ ]:
SEED = 1234

# Set seed for reproducibility
np.random.seed(seed=SEED)
tf.random.set_seed(SEED)

# Basic

ตัวอย่างสร้างค่าคงที่

In [ ]:
# Constants
x = tf.constant(1)
print (x)

tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
x = tf.constant([ [1, 2, 3] , [4, 5, 6] ])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


ตัวอย่างสร้าง tensor ขนาด 2 x 3 ซึ่งสมาชิกข้างในมัน random ด้วยรูปแบบ uniform distribution

In [ ]:
# Creating a random tensor
x = tf.random.uniform((2,3))
print(f"Type: {x.dtype}")
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Type: <dtype: 'float32'>
Size: (2, 3)
Values: 
[[0.5380393  0.36461866 0.5816301 ]
 [0.24382842 0.43033564 0.90619123]]


ตัวอย่างเรียกใช้เมธอด numpy()

In [ ]:
print(x.numpy())

[[0.5380393  0.36461866 0.5816301 ]
 [0.24382842 0.43033564 0.90619123]]


ตัวอย่างสร้าง tensor ขนาด 2x3 ที่สมาชิกเป็น 0 กับ 1

In [ ]:
# Zero and Ones tensor
x = tf.zeros((2, 3))
print (x)
x = tf.ones((2, 3))
print (x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


แปลงชนิดข้อมูลจาก List เป็น Tensor

In [ ]:
# List → Tensor
x = tf.convert_to_tensor([[1, 2, 3],[4, 5, 6]], dtype='int32')
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Size: (2, 3)
Values: 
[[1 2 3]
 [4 5 6]]


แปลงชนิดข้อมูลจาก Numpy เป็น Tensor

In [ ]:
# NumPy array → Tensor
x = tf.convert_to_tensor(np.random.rand(2, 3), dtype='float32')
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Size: (2, 3)
Values: 
[[0.19151945 0.62210876 0.43772775]
 [0.7853586  0.77997583 0.2725926 ]]


แปลงชนิดข้อมูลจาก DataFrame เป็น Tensor


In [ ]:
import pandas as pd

df = pd.read_csv("https://download.mlcc.google.com/mledu-datasets/california_housing_train.csv", sep=",")
print("Size of dataframe:", np.shape(df))

#x = torch.from_numpy(df.values)
x = tf.convert_to_tensor(df.values)

print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Size of dataframe: (17000, 9)
Size: (17000, 9)
Values: 
[[-1.1431e+02  3.4190e+01  1.5000e+01 ...  4.7200e+02  1.4936e+00
   6.6900e+04]
 [-1.1447e+02  3.4400e+01  1.9000e+01 ...  4.6300e+02  1.8200e+00
   8.0100e+04]
 [-1.1456e+02  3.3690e+01  1.7000e+01 ...  1.1700e+02  1.6509e+00
   8.5700e+04]
 ...
 [-1.2430e+02  4.1840e+01  1.7000e+01 ...  4.5600e+02  3.0313e+00
   1.0360e+05]
 [-1.2430e+02  4.1800e+01  1.9000e+01 ...  4.7800e+02  1.9797e+00
   8.5800e+04]
 [-1.2435e+02  4.0540e+01  5.2000e+01 ...  2.7000e+02  3.0147e+00
   9.4600e+04]]


เปลี่ยนชนิดข้อมูลใน tensor


In [ ]:
# Changing tensor type
'''
x = tf.random.uniform((2,3))
print(f"Type: {x.dtype}")
x = tf.random.uniform((2,3), dtype='float64')
print(f"Type: {x.dtype}")
'''
x = tf.random.uniform((2,3))
print(f"Type: {x.dtype}")
x = tf.convert_to_tensor(x.numpy(), dtype='float64')
print(f"Type: {x.dtype}")


Type: <dtype: 'float32'>
Type: <dtype: 'float64'>


# ตัวดำนำการ (Operations)

In [ ]:
# Addition
x = tf.random.uniform((2,3))
y = tf.random.uniform((2,3))
z = x + y
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

Size: (2, 3)
Values: 
[[1.5074273  0.9708134  1.1970681 ]
 [1.1366602  0.46226835 0.5434133 ]]


บวกลบคูณหารแบบเมทริกซ์

In [ ]:
a = tf.random.uniform((2,3))
b = tf.random.uniform((2,3))
c = tf.random.uniform((2,3))
z = (a**2 - 4*b )/c
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

Size: (2, 3)
Values: 
[[ -2.2354162 -11.57526    -4.132743 ]
 [ -5.5883336  -2.9325957  -1.6236894]]


In [ ]:
# Dot product
x = tf.random.uniform((2,3))
y = tf.random.uniform((3,2))
z = tf.matmul(x, y)
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

Size: (2, 2)
Values: 
[[0.88974315 0.36487216]
 [0.30922678 0.18126723]]


ทำทรานโพส

In [ ]:
# Transpose
x = tf.random.uniform((2,3))
print(f"Size: {x.shape}")
print(f"Values: \n{x}")
y = tf.transpose(x)
print(f"Size: {y.shape}")
print(f"Values: \n{y}")

Size: (2, 3)
Values: 
[[0.45171046 0.9757304  0.96276057]
 [0.49976635 0.46484458 0.65036225]]
Size: (3, 2)
Values: 
[[0.45171046 0.49976635]
 [0.9757304  0.46484458]
 [0.96276057 0.65036225]]


เปลี่ยนขนาด

In [ ]:
# Reshape
x = tf.random.uniform((2,3))
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

z = tf.reshape(x, (3, 2))
print("\nAfter Reshape")
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

z = tf.reshape(x, (1, 6))
print("\nAfter Reshape")
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

Size: (2, 3)
Values: 
[[0.80235374 0.6862793  0.35347772]
 [0.5970619  0.8998532  0.05612409]]

After Reshape
Size: (3, 2)
Values: 
[[0.80235374 0.6862793 ]
 [0.35347772 0.5970619 ]
 [0.8998532  0.05612409]]

After Reshape
Size: (1, 6)
Values: 
[[0.80235374 0.6862793  0.35347772 0.5970619  0.8998532  0.05612409]]


operator แนวแกนตั้ง (คอลัมน์) หรือนอน (แถว)

* dim = 0 คือแกนตั้ง
* dim = 1 คือแกนนอน

In [ ]:
# Dimensional operations
x = tf.random.uniform((2,3))
print(f"Values: \n{x}")
y = tf.math.reduce_sum(x, axis=0) # add each row's value for every column
print(f"Values: \n{y}")
z = tf.math.reduce_sum(x, axis=1) # add each columns's value for every row
print(f"Values: \n{z}")

Values: 
[[0.13242006 0.8582847  0.50360227]
 [0.7038616  0.42338693 0.7614349 ]]
Values: 
[0.83628166 1.2816716  1.2650372 ]
Values: 
[1.494307  1.8886834]


# Indexing, Splicing and Joining

ใช้ index เหมือนกับ numpy

In [ ]:
x = tf.random.uniform((2,3))
print (f"x: \n{x}")
print (f"x[:1]: \n{x[:1]}")
print (f"x[:1, 1:3]: \n{x[:1, 1:3]}")

x: 
[[0.46948004 0.64634395 0.07618201]
 [0.39206338 0.23859632 0.16841686]]
x[:1]: 
[[0.46948004 0.64634395 0.07618201]]
x[:1, 1:3]: 
[[0.64634395 0.07618201]]


In [ ]:
# Select with dimensional indicies
x = tf.random.uniform((2,3))
print(f"Values: \n{x}")

col_indices = tf.convert_to_tensor([0, 2])
chosen = tf.gather(x, indices=col_indices, axis=1) # values from column 0 & 2
print(f"Values: \n{chosen}") 

Values: 
[[0.37195098 0.86123586 0.7835368 ]
 [0.2759757  0.26125538 0.8507333 ]]
Values: 
[[0.37195098 0.7835368 ]
 [0.2759757  0.8507333 ]]


นำ tensor มาต่อกัน

In [ ]:
# Concatenation
x = tf.random.uniform((2,3))
print(f"Values: \n{x}")
y = tf.concat([x, x], axis=0) # stack by rows (axis=1 to stack by columns)
print(f"Values: \n{y}")

Values: 
[[0.45885837 0.5560707  0.19083893]
 [0.7622721  0.94571674 0.78334343]]
Values: 
[[0.45885837 0.5560707  0.19083893]
 [0.7622721  0.94571674 0.78334343]
 [0.45885837 0.5560707  0.19083893]
 [0.7622721  0.94571674 0.78334343]]


# Gradients

# Accurarcy

In [ ]:
m = tf.keras.metrics.Accuracy()
_ = m.update_state([[1], [2], [3], [4]], [[0], [2], [3], [4]])
m.result().numpy()

0.75

# ฝากติดตาม

<img height="20px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2017/06/logo_facebook2.png" align="left" hspace="10px" vspace="0px">  https://www.facebook.com/programmerthai/

<img height="14px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2019/03/youtube.png" align="left" hspace="10px" vspace="3px">  https://www.youtube.com/channel/UCvhCKtG5cRE6K5--RJPql_w

<img height="14px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2019/09/github-2.jpg" align="left" hspace="10px" vspace="3px">https://github.com/adminho/machine-learning

In [ ]:
#@title ฝากประชาสัมพันธ์ หนังสือ AI (ปัญญาประดิษฐ์) ไม่ยาก เรียนรู้ได้ด้วยเลขม. ปลาย ราคา 295 บาท
%%HTML
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fprogrammerthai%2Fphotos%2Fa.2410667485889755%2F2555677101388792%2F%3Ftype%3D3&width=500" width="500" height="588" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>