<a href="https://colab.research.google.com/github/tiravata/2014-slides/blob/master/134_tutorial_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div><img height="45px" src="https://avatars3.githubusercontent.com/u/20337240?s=460&v=4" align="left" hspace="10px" vspace="0px">
</div>
<h1>ติวเตอร์ PyTorch</h1>

<hr>

<a href='https://www.facebook.com/programmerthai'><font color='green'>สรุปและเรียบเรียงโดย โปรแกรมเมอร์ไทย thai programmer</font></a>



cite

https://colab.research.google.com/github/madewithml/lessons/blob/master/notebooks/01_Foundations/06_PyTorch.ipynb

https://medium.com/dair-ai/pytorch-1-2-quickstart-with-google-colab-6690a30c38d

# วิธีใช้งาน colab

Colab พัฒนาโดย google เป็นหน้าเว็บเอาไว้ใช้เขียนโค้ด python ได้ผ่านทางหน้าเว็บ และเชื่อมต่อกับ google drive ของเราก็ได้ด้วย ซึ่ง colab หน้านี้**ได้รวบรวมเนื้อหา Python ของม.ต้น** เอาไว้ แต่ก่อนอื่นอยากให้ดูวิธีการใช้งาน colab เสียก่อน

<font color='red'>** ต้องมี Gmail และ google drive</font>

<hr/>

<h3>วิธี 1) กด "Open in playgrouhd"</h3>
<div>
<img height="200px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2020/05/python_matayom_4.png" align="center" hspace="10px" vspace="0px">


<hr/>

<h3>วิธี 2) กด Save a copy in Drive ... เพื่อบันทึกไว้ google drive เครื่องเรา</h3>

<img height="300px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2019/11/python_matayom_1.png" align="center" hspace="10px" vspace="0px">

<br/>

<img height="200px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2019/11/python_matayom_2.png" align="center" hspace="10px" vspace="0px">

<hr/>

<h3>จากนั้นถึงจะสามารถรันได้</h3>
<img height="200px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2019/11/python_matayom_3.png" align="center" hspace="10px" vspace="0px">

# Set Environments

In [ ]:
import numpy as np
import torch

# ใช้งาน GPUs

ตรวจสอบใช้งาน CUDA หรือไม่

In [ ]:
# Is CUDA available now?
print (torch.cuda.is_available())

True


ถ้า False แสดงว่า CUDA ไม่ได้เปิดใช้งาน

แนะนำให้ไปที่  *Runtime* > *Change runtime type* > Change *Hardware accelertor* to *GPU* > Click *Save*

In [ ]:
# Set device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print (device)

cuda


เลือกว่าจะใช้ tensor บน CPU หรือ GPU

In [ ]:
x = torch.rand(2,3)
print (x.is_cuda) # sTensor is store on the CPU

x = torch.rand(2,3).to(device) # sTensor is stored on the GPU
print (x.is_cuda)

print( type(x) )

False
True
<class 'torch.Tensor'>


# Set seeds

In [ ]:
SEED = 1234

# Set seed for reproducibility
np.random.seed(seed=SEED)
torch.manual_seed(SEED)

# Basics

ตัวอย่างสร้าง tensor ขนาด 2 x 3 ซึ่งสมาชิกข้างในมัน random ด้วยรูปแบบ uniform distribution

In [ ]:
# Creating a random tensor
x = torch.randn(2, 3) # normal distribution (rand(2,3) -> uniform distribution)
print(f"Type: {x.type()}")
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Type: torch.FloatTensor
Size: torch.Size([2, 3])
Values: 
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


ตัวอย่างเรียกใช้ method ของ tensor (มีเยอะ)

In [ ]:
print(x.data)
print(x.values)
print(x.min())
print(x.max())
print(x.pow(3))
print(x.sigmoid())
print(x.sin())
print(x.std())
print(x.sum())

tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])
<built-in method values of Tensor object at 0x7f21d38abd80>
tensor(-1.0115)
tensor(0.5036)
tensor([[ 9.8167e-05,  6.5160e-02, -1.0350e+00],
        [ 1.0181e-02, -2.2953e-01,  1.2773e-01]])
tensor([[0.5115, 0.5993, 0.2667],
        [0.5540, 0.3515, 0.6233]])
tensor([[ 0.0461,  0.3916, -0.8476],
        [ 0.2150, -0.5747,  0.4826]])
tensor(0.6047)
tensor(-0.4549)


ตัวอย่างสร้าง tensor ขนาด 2x3 ที่สมาชิกเป็น 0 กับ 1

In [ ]:
# Zero and Ones tensor
x = torch.zeros(2, 3)
print (x)
x = torch.ones(2, 3)
print (x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


แปลงชนิดข้อมูลจาก List เป็น Tensor

In [ ]:
# List → Tensor
x = torch.Tensor([[1, 2, 3],[4, 5, 6]])
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


แปลงชนิดข้อมูลจาก Numpy เป็น Tensor

In [ ]:
# NumPy array → Tensor
x = torch.Tensor(np.random.rand(2, 3))
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Size: torch.Size([2, 3])
Values: 
tensor([[0.1915, 0.6221, 0.4377],
        [0.7854, 0.7800, 0.2726]])


แปลงชนิดข้อมูลจาก DataFrame เป็น Tensor


In [ ]:
import pandas as pd

df = pd.read_csv("https://download.mlcc.google.com/mledu-datasets/california_housing_train.csv", sep=",")
print("Size of dataframe:", np.shape(df))

#x = torch.from_numpy(df.values)
x = torch.Tensor(df.values)

print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Size of dataframe: (17000, 9)
Size: torch.Size([17000, 9])
Values: 
tensor([[-1.1431e+02,  3.4190e+01,  1.5000e+01,  ...,  4.7200e+02,
          1.4936e+00,  6.6900e+04],
        [-1.1447e+02,  3.4400e+01,  1.9000e+01,  ...,  4.6300e+02,
          1.8200e+00,  8.0100e+04],
        [-1.1456e+02,  3.3690e+01,  1.7000e+01,  ...,  1.1700e+02,
          1.6509e+00,  8.5700e+04],
        ...,
        [-1.2430e+02,  4.1840e+01,  1.7000e+01,  ...,  4.5600e+02,
          3.0313e+00,  1.0360e+05],
        [-1.2430e+02,  4.1800e+01,  1.9000e+01,  ...,  4.7800e+02,
          1.9797e+00,  8.5800e+04],
        [-1.2435e+02,  4.0540e+01,  5.2000e+01,  ...,  2.7000e+02,
          3.0147e+00,  9.4600e+04]])


เปลี่ยนชนิดข้อมูลใน tensor


In [ ]:
# Changing tensor type
x = torch.Tensor(3, 4)
print(f"Type: {x.type()}")
x = x.long()
print(f"Type: {x.type()}")

Type: torch.FloatTensor
Type: torch.LongTensor


# ตัวดำนำการ (Operations)

In [ ]:
# Addition
x = torch.randn(2, 3)
y = torch.randn(2, 3)
z = x + y
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

Size: torch.Size([2, 3])
Values: 
tensor([[ 0.0761, -0.6775, -0.3988],
        [ 3.0633, -0.1589,  0.3514]])


บวกลบคูณหารแบบเมทริกซ์

In [ ]:
a = torch.randn(2, 3)
b = torch.randn(2, 3)
c = torch.randn(2, 3)
z = (a**2 - 4*b )/c
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

Size: torch.Size([2, 3])
Values: 
tensor([[ -0.9559, -12.4893,  10.9259],
        [ -0.1228,   2.1366,   1.3720]])


การคูณเมทริกซ์

In [ ]:
# Dot product
x = torch.randn(2, 3)
y = torch.randn(3, 2)
z = torch.mm(x, y)
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

Size: torch.Size([2, 2])
Values: 
tensor([[ 0.5177,  1.2599],
        [-0.2197,  0.5813]])


ทำทรานโพส

In [ ]:
# Transpose
x = torch.randn(2, 3)
print(f"Size: {x.shape}")
print(f"Values: \n{x}")
y = torch.t(x)
print(f"Size: {y.shape}")
print(f"Values: \n{y}")

Size: torch.Size([2, 3])
Values: 
tensor([[0.2111, 0.3372, 0.6638],
        [1.0397, 1.8434, 0.6588]])
Size: torch.Size([3, 2])
Values: 
tensor([[0.2111, 1.0397],
        [0.3372, 1.8434],
        [0.6638, 0.6588]])


เปลี่ยนขนาด

In [ ]:
# Reshape
x = torch.randn(2, 3)
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

z = x.view(3, 2)
print("\nAfter Reshape")
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

z = x.view(1, 6)
print("\nAfter Reshape")
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

Size: torch.Size([2, 3])
Values: 
tensor([[-0.2349, -0.0306,  1.7462],
        [-0.0722, -1.6794, -1.7010]])

After Reshape
Size: torch.Size([3, 2])
Values: 
tensor([[-0.2349, -0.0306],
        [ 1.7462, -0.0722],
        [-1.6794, -1.7010]])

After Reshape
Size: torch.Size([1, 6])
Values: 
tensor([[-0.2349, -0.0306,  1.7462, -0.0722, -1.6794, -1.7010]])


In [ ]:
# Dangers of reshaping (unintended consequences)
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print(f"Size: {x.shape}")
print(f"x: \n{x}\n")

a = x.view(x.size(1), -1)
print(f"\nSize: {a.shape}")
print(f"a: \n{a}\n")

b = x.transpose(0,1).contiguous()
print(f"\nSize: {b.shape}")
print(f"b: \n{b}\n")

c = b.view(b.size(0), -1)
print(f"\nSize: {c.shape}")
print(f"c: \n{c}")

Size: torch.Size([2, 3, 4])
x: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
a: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])


Size: torch.Size([3, 2, 4])
b: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
c: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


operator แนวแกนตั้ง (คอลัมน์) หรือนอน (แถว)

* dim = 0 คือแกนตั้ง
* dim = 1 คือแกนนอน

In [ ]:
# Dimensional operations
x = torch.randn(2, 3)
print(f"Values: \n{x}")
y = torch.sum(x, dim=0) # add each row's value for every column
print(f"Values: \n{y}")
z = torch.sum(x, dim=1) # add each columns's value for every row
print(f"Values: \n{z}")

Values: 
tensor([[ 0.6486,  1.7653,  1.0812],
        [ 1.2436,  0.8971, -0.0784]])
Values: 
tensor([1.8922, 2.6624, 1.0028])
Values: 
tensor([3.4951, 2.0623])


# Indexing, Splicing and Joining

ใช้ index เหมือนกับ numpy

In [ ]:
x = torch.randn(3, 4)
print (f"x: \n{x}")
print (f"x[:1]: \n{x[:1]}")
print (f"x[:1, 1:3]: \n{x[:1, 1:3]}")

print(f"x[1, 2]: \n{x[1,2]}")

x: 
tensor([[ 0.5548, -0.0845,  0.5903, -1.0032],
        [-1.7873,  0.0538,  0.8246, -0.5723],
        [-0.4876,  0.1944, -1.0481, -0.0741]])
x[:1]: 
tensor([[ 0.5548, -0.0845,  0.5903, -1.0032]])
x[:1, 1:3]: 
tensor([[-0.0845,  0.5903]])
x[1, 2]: 
0.8245806097984314


In [ ]:
# Select with dimensional indicies
x = torch.randn(2, 3)
print(f"Values: \n{x}")

col_indices = torch.LongTensor([0, 2])
chosen = torch.index_select(x, dim=1, index=col_indices) # values from column 0 & 2
print(f"Values: \n{chosen}") 

row_indices = torch.LongTensor([0, 1])
col_indices = torch.LongTensor([0, 2])
chosen = x[row_indices, col_indices] # values from (0, 0) & (2, 1)
print(f"Values: \n{chosen}") 

Values: 
tensor([[-0.3449, -1.5447,  0.0685],
        [-1.5104, -1.1706,  0.2259]])
Values: 
tensor([[-0.3449,  0.0685],
        [-1.5104,  0.2259]])
Values: 
tensor([-0.3449,  0.2259])


นำ tensor มาต่อกัน

In [ ]:
# Concatenation
x = torch.randn(2, 3)
print(f"Values: \n{x}")
y = torch.cat([x, x], dim=0) # stack by rows (dim=1 to stack by columns)
print(f"Values: \n{y}")

Values: 
tensor([[ 1.4696, -1.3284,  1.9946],
        [-0.8209,  1.0061, -1.0664]])
Values: 
tensor([[ 1.4696, -1.3284,  1.9946],
        [-0.8209,  1.0061, -1.0664],
        [ 1.4696, -1.3284,  1.9946],
        [-0.8209,  1.0061, -1.0664]])


# การหา Gradients

In [ ]:
# Tensors with gradient bookkeeping
x = torch.rand(3, 4, requires_grad=True)
y = 3*x + 2
z = y.mean()
z.backward() # z has to be scalar
print(f"x: \n{x}")
print(f"x.grad: \n{x.grad}")

x: 
tensor([[0.0586, 0.8958, 0.5129, 0.7490],
        [0.2254, 0.4485, 0.5658, 0.3631],
        [0.9719, 0.2716, 0.6552, 0.1607]], requires_grad=True)
x.grad: 
tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


<img src="https://scontent.fnak3-1.fna.fbcdn.net/v/t1.0-9/s960x960/95531413_2612820449007790_578337313709359104_o.png?_nc_cat=108&_nc_sid=0be424&_nc_ohc=sAdGJkIzyLAAX8kWlN4&_nc_ht=scontent.fnak3-1.fna&oh=d98b75c0720670e946c83cecb8f8bdaa&oe=5F106E3C" width="400">

**ตัวอย่างโค้ดเพื่อแก้โจทย์ดังกล่าว**

In [ ]:
import torch
x = torch.Tensor([0.1, 0.7])
x.requires_grad=True
y = x[0]**2 + 2*x[1] + 1
z = 3*y - 1
z.backward()

print(x.grad)

tensor([0.6000, 6.0000])


# ฝากติดตาม

<img height="20px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2017/06/logo_facebook2.png" align="left" hspace="10px" vspace="0px">  https://www.facebook.com/programmerthai/

<img height="14px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2019/03/youtube.png" align="left" hspace="10px" vspace="3px">  https://www.youtube.com/channel/UCvhCKtG5cRE6K5--RJPql_w

<img height="14px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2019/09/github-2.jpg" align="left" hspace="10px" vspace="3px">https://github.com/adminho/machine-learning

In [ ]:
#@title ฝากประชาสัมพันธ์ หนังสือ AI (ปัญญาประดิษฐ์) ไม่ยาก เรียนรู้ได้ด้วยเลขม. ปลาย ราคา 295 บาท
%%HTML
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fprogrammerthai%2Fphotos%2Fa.2410667485889755%2F2555677101388792%2F%3Ftype%3D3&width=500" width="500" height="588" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>